### ISSUE TITLE
Fill empty slots with blank scorecards and add option for generating blank scorecards

### ISSUE THREAD

**Issue by DanielEgdal** [Daniel-Anker-Hermansen/WCA_Scorecards#2]
When a slot is not used, generate a blank scorecard instead of the blank slot. This should save paper.

Additionally, add the possibility of calling the program with a flag for blank scorecards. By default, just make a page with 5 attempts, and one page with 3 attempts.

**Comment by Daniel-Anker-Hermansen** [comment]
Implemented with blank subcommand.
