### ISSUE TITLE
Rework arguments to separate commands from options

### ISSUE THREAD

**Issue by Daniel-Anker-Hermansen** [Daniel-Anker-Hermansen/WCA_Scorecards#3]
CLI arguments currently do not follow convention. This will require breaking changes.
- [x] Consider command names for current ```--r1``` and --```subseq``` should (Maybe ```csv``` and ```wcif```?)
- [x] Consider command name for coming blank scorecards
- [x] Consider better ways of inputting complicated options like for ```--stages```
- [x] Maybe implement presets so that a preset is created for a competition and stages etc. does not have to continuously be entered (What should the syntax be? Where should the presets be stored (call site/default path?))

**Comment by Daniel-Anker-Hermansen** [comment]
@DanielEgdal Any thought on this?

**Comment by DanielEgdal** [comment]
1: `csv` and `wcif`
2: `blank`
3: `stages {num_stages} {amount_per_stage}`

**Comment by Daniel-Anker-Hermansen** [comment]
- [x] actually implement it.
